package com.ag.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Accesstoken generated by hbm2java
 */
@Entity
@Table(name = "accesstoken", catalog = "3d_customer_api")
public class Accesstoken implements java.io.Serializable {

	private String id;
	private Integer ttl;
	private String scopes;
	private Date created;
	private Integer userId;

	public Accesstoken() {
	}

	public Accesstoken(String id) {
		this.id = id;
	}

	public Accesstoken(String id, Integer ttl, String scopes, Date created, Integer userId) {
		this.id = id;
		this.ttl = ttl;
		this.scopes = scopes;
		this.created = created;
		this.userId = userId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ttl")
	public Integer getTtl() {
		return this.ttl;
	}

	public void setTtl(Integer ttl) {
		this.ttl = ttl;
	}

	@Column(name = "scopes", length = 65535)
	public String getScopes() {
		return this.scopes;
	}

	public void setScopes(String scopes) {
		this.scopes = scopes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
