package com.ag.model;
// default package
// Generated Mar 21, 2018 6:20:13 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Acl generated by hbm2java
 */
@Entity
@Table(name = "acl", catalog = "3d_customer_api")
public class Acl implements java.io.Serializable {

	private Integer id;
	private String model;
	private String property;
	private String accessType;
	private String permission;
	private String principalType;
	private String principalId;

	public Acl() {
	}

	public Acl(String model, String property, String accessType, String permission, String principalType,
			String principalId) {
		this.model = model;
		this.property = property;
		this.accessType = accessType;
		this.permission = permission;
		this.principalType = principalType;
		this.principalId = principalId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "model", length = 512)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "property", length = 512)
	public String getProperty() {
		return this.property;
	}

	public void setProperty(String property) {
		this.property = property;
	}

	@Column(name = "accessType", length = 512)
	public String getAccessType() {
		return this.accessType;
	}

	public void setAccessType(String accessType) {
		this.accessType = accessType;
	}

	@Column(name = "permission", length = 512)
	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	@Column(name = "principalType", length = 512)
	public String getPrincipalType() {
		return this.principalType;
	}

	public void setPrincipalType(String principalType) {
		this.principalType = principalType;
	}

	@Column(name = "principalId", length = 512)
	public String getPrincipalId() {
		return this.principalId;
	}

	public void setPrincipalId(String principalId) {
		this.principalId = principalId;
	}

}
