package com.ag.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rolemapping generated by hbm2java
 */
@Entity
@Table(name = "rolemapping", catalog = "3d_customer_api")
public class Rolemapping implements java.io.Serializable {

	private Integer id;
	private String principalType;
	private String principalId;
	private Integer roleId;

	public Rolemapping() {
	}

	public Rolemapping(String principalType, String principalId, Integer roleId) {
		this.principalType = principalType;
		this.principalId = principalId;
		this.roleId = roleId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "principalType", length = 512)
	public String getPrincipalType() {
		return this.principalType;
	}

	public void setPrincipalType(String principalType) {
		this.principalType = principalType;
	}

	@Column(name = "principalId")
	public String getPrincipalId() {
		return this.principalId;
	}

	public void setPrincipalId(String principalId) {
		this.principalId = principalId;
	}

	@Column(name = "roleId")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

}
