package com.ag.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblCollectionAccountFrame generated by hbm2java
 */
@Entity
@Table(name = "tbl_collection_account_frame", catalog = "3d_customer_api")
public class TblCollectionAccountFrame implements java.io.Serializable {

	private Integer id;
	private TblCollectionAccount tblCollectionAccount;
	private TblInvAccountFrame tblInvAccountFrame;
	private int order;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;

	public TblCollectionAccountFrame() {
	}

	public TblCollectionAccountFrame(TblCollectionAccount tblCollectionAccount, TblInvAccountFrame tblInvAccountFrame,
			int order, byte isDeleted, Date createDatetime) {
		this.tblCollectionAccount = tblCollectionAccount;
		this.tblInvAccountFrame = tblInvAccountFrame;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblCollectionAccountFrame(TblCollectionAccount tblCollectionAccount, TblInvAccountFrame tblInvAccountFrame,
			int order, byte isDeleted, Date createDatetime, Date updateDatetime) {
		this.tblCollectionAccount = tblCollectionAccount;
		this.tblInvAccountFrame = tblInvAccountFrame;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "collection_account_id", nullable = false)
	public TblCollectionAccount getTblCollectionAccount() {
		return this.tblCollectionAccount;
	}

	public void setTblCollectionAccount(TblCollectionAccount tblCollectionAccount) {
		this.tblCollectionAccount = tblCollectionAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_frameid", nullable = false)
	public TblInvAccountFrame getTblInvAccountFrame() {
		return this.tblInvAccountFrame;
	}

	public void setTblInvAccountFrame(TblInvAccountFrame tblInvAccountFrame) {
		this.tblInvAccountFrame = tblInvAccountFrame;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
