package com.ag.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblCollectionDistFrame generated by hbm2java
 */
@Entity
@Table(name = "tbl_collection_dist_frame", catalog = "3d_customer_api")
public class TblCollectionDistFrame implements java.io.Serializable {

	private Integer id;
	private TblCollectionDist tblCollectionDist;
	private TblInvDistFrame tblInvDistFrame;
	private int order;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;

	public TblCollectionDistFrame() {
	}

	public TblCollectionDistFrame(TblCollectionDist tblCollectionDist, TblInvDistFrame tblInvDistFrame, int order,
			byte isDeleted, Date createDatetime) {
		this.tblCollectionDist = tblCollectionDist;
		this.tblInvDistFrame = tblInvDistFrame;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblCollectionDistFrame(TblCollectionDist tblCollectionDist, TblInvDistFrame tblInvDistFrame, int order,
			byte isDeleted, Date createDatetime, Date updateDatetime) {
		this.tblCollectionDist = tblCollectionDist;
		this.tblInvDistFrame = tblInvDistFrame;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "collection_dist_id", nullable = false)
	public TblCollectionDist getTblCollectionDist() {
		return this.tblCollectionDist;
	}

	public void setTblCollectionDist(TblCollectionDist tblCollectionDist) {
		this.tblCollectionDist = tblCollectionDist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "collection_dist_frame_id", nullable = false)
	public TblInvDistFrame getTblInvDistFrame() {
		return this.tblInvDistFrame;
	}

	public void setTblInvDistFrame(TblInvDistFrame tblInvDistFrame) {
		this.tblInvDistFrame = tblInvDistFrame;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
