package com.ag.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblInvDistFrame generated by hbm2java
 */
@Entity
@Table(name = "tbl_inv_dist_frame", catalog = "3d_customer_api")
public class TblInvDistFrame implements java.io.Serializable {

	private Integer id;
	private TblInvFrameMetadata tblInvFrameMetadata;
	private TblUser tblUser;
	private int quantity;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private BigDecimal price;
	private String priceUnit;
	private BigDecimal priceMrp;
	private Set<TblOrderitems> tblOrderitemses = new HashSet<TblOrderitems>(0);
	private Set<TblCollectionDistFrame> tblCollectionDistFrames = new HashSet<TblCollectionDistFrame>(0);
	private Set<TblInvAccountFrame> tblInvAccountFrames = new HashSet<TblInvAccountFrame>(0);

	public TblInvDistFrame() {
	}

	public TblInvDistFrame(TblInvFrameMetadata tblInvFrameMetadata, TblUser tblUser, int quantity, byte isDeleted,
			Date createDatetime) {
		this.tblInvFrameMetadata = tblInvFrameMetadata;
		this.tblUser = tblUser;
		this.quantity = quantity;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblInvDistFrame(TblInvFrameMetadata tblInvFrameMetadata, TblUser tblUser, int quantity, byte isDeleted,
			Date createDatetime, Date updateDatetime, BigDecimal price, String priceUnit, BigDecimal priceMrp,
			Set<TblOrderitems> tblOrderitemses, Set<TblCollectionDistFrame> tblCollectionDistFrames,
			Set<TblInvAccountFrame> tblInvAccountFrames) {
		this.tblInvFrameMetadata = tblInvFrameMetadata;
		this.tblUser = tblUser;
		this.quantity = quantity;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.price = price;
		this.priceUnit = priceUnit;
		this.priceMrp = priceMrp;
		this.tblOrderitemses = tblOrderitemses;
		this.tblCollectionDistFrames = tblCollectionDistFrames;
		this.tblInvAccountFrames = tblInvAccountFrames;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frameid", nullable = false)
	public TblInvFrameMetadata getTblInvFrameMetadata() {
		return this.tblInvFrameMetadata;
	}

	public void setTblInvFrameMetadata(TblInvFrameMetadata tblInvFrameMetadata) {
		this.tblInvFrameMetadata = tblInvFrameMetadata;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dist_userid", nullable = false)
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@Column(name = "price", precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "price_unit", length = 20)
	public String getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(String priceUnit) {
		this.priceUnit = priceUnit;
	}

	@Column(name = "price_mrp", precision = 10)
	public BigDecimal getPriceMrp() {
		return this.priceMrp;
	}

	public void setPriceMrp(BigDecimal priceMrp) {
		this.priceMrp = priceMrp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvDistFrame")
	public Set<TblOrderitems> getTblOrderitemses() {
		return this.tblOrderitemses;
	}

	public void setTblOrderitemses(Set<TblOrderitems> tblOrderitemses) {
		this.tblOrderitemses = tblOrderitemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvDistFrame")
	public Set<TblCollectionDistFrame> getTblCollectionDistFrames() {
		return this.tblCollectionDistFrames;
	}

	public void setTblCollectionDistFrames(Set<TblCollectionDistFrame> tblCollectionDistFrames) {
		this.tblCollectionDistFrames = tblCollectionDistFrames;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvDistFrame")
	public Set<TblInvAccountFrame> getTblInvAccountFrames() {
		return this.tblInvAccountFrames;
	}

	public void setTblInvAccountFrames(Set<TblInvAccountFrame> tblInvAccountFrames) {
		this.tblInvAccountFrames = tblInvAccountFrames;
	}

}
