package com.ag.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblInvGender generated by hbm2java
 */
@Entity
@Table(name = "tbl_inv_gender", catalog = "3d_customer_api", uniqueConstraints = @UniqueConstraint(columnNames = "gender"))
public class TblInvGender implements java.io.Serializable {

	private Integer id;
	private String gender;
	private String genderIcon;
	private int order;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private Set<TblModel> tblModels = new HashSet<TblModel>(0);
	private Set<TblInvFrameMetadata> tblInvFrameMetadatas = new HashSet<TblInvFrameMetadata>(0);

	public TblInvGender() {
	}

	public TblInvGender(String gender, int order, byte isDeleted, Date createDatetime) {
		this.gender = gender;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblInvGender(String gender, String genderIcon, int order, byte isDeleted, Date createDatetime,
			Date updateDatetime, Set<TblModel> tblModels, Set<TblInvFrameMetadata> tblInvFrameMetadatas) {
		this.gender = gender;
		this.genderIcon = genderIcon;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.tblModels = tblModels;
		this.tblInvFrameMetadatas = tblInvFrameMetadatas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "gender", unique = true, nullable = false, length = 100)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "gender_icon", length = 200)
	public String getGenderIcon() {
		return this.genderIcon;
	}

	public void setGenderIcon(String genderIcon) {
		this.genderIcon = genderIcon;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvGender")
	public Set<TblModel> getTblModels() {
		return this.tblModels;
	}

	public void setTblModels(Set<TblModel> tblModels) {
		this.tblModels = tblModels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvGender")
	public Set<TblInvFrameMetadata> getTblInvFrameMetadatas() {
		return this.tblInvFrameMetadatas;
	}

	public void setTblInvFrameMetadatas(Set<TblInvFrameMetadata> tblInvFrameMetadatas) {
		this.tblInvFrameMetadatas = tblInvFrameMetadatas;
	}

}
