package com.ag.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblInvBrand generated by hbm2java
 */
@Entity
@Table(name = "tbl_inv_brand", catalog = "3d_customer_api", uniqueConstraints = @UniqueConstraint(columnNames = "brand"))
public class TblInvBrand implements java.io.Serializable {

	private Integer id;
	private TblInvCompany tblInvCompany;
	private String brand;
	private String brandIconUrl;
	private String brandBannerimageUrl;
	private byte isGeneric;
	private int order;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private Set<TblInvFrameMetadata> tblInvFrameMetadatas = new HashSet<TblInvFrameMetadata>(0);

	public TblInvBrand() {
	}

	public TblInvBrand(TblInvCompany tblInvCompany, String brand, byte isGeneric, int order, byte isDeleted,
			Date createDatetime) {
		this.tblInvCompany = tblInvCompany;
		this.brand = brand;
		this.isGeneric = isGeneric;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblInvBrand(TblInvCompany tblInvCompany, String brand, String brandIconUrl, String brandBannerimageUrl,
			byte isGeneric, int order, byte isDeleted, Date createDatetime, Date updateDatetime,
			Set<TblInvFrameMetadata> tblInvFrameMetadatas) {
		this.tblInvCompany = tblInvCompany;
		this.brand = brand;
		this.brandIconUrl = brandIconUrl;
		this.brandBannerimageUrl = brandBannerimageUrl;
		this.isGeneric = isGeneric;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.tblInvFrameMetadatas = tblInvFrameMetadatas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "company_id", nullable = false)
	public TblInvCompany getTblInvCompany() {
		return this.tblInvCompany;
	}

	public void setTblInvCompany(TblInvCompany tblInvCompany) {
		this.tblInvCompany = tblInvCompany;
	}

	@Column(name = "brand", unique = true, nullable = false, length = 100)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "brand_icon_url", length = 200)
	public String getBrandIconUrl() {
		return this.brandIconUrl;
	}

	public void setBrandIconUrl(String brandIconUrl) {
		this.brandIconUrl = brandIconUrl;
	}

	@Column(name = "brand_bannerimage_url", length = 200)
	public String getBrandBannerimageUrl() {
		return this.brandBannerimageUrl;
	}

	public void setBrandBannerimageUrl(String brandBannerimageUrl) {
		this.brandBannerimageUrl = brandBannerimageUrl;
	}

	@Column(name = "is_generic", nullable = false)
	public byte getIsGeneric() {
		return this.isGeneric;
	}

	public void setIsGeneric(byte isGeneric) {
		this.isGeneric = isGeneric;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvBrand")
	public Set<TblInvFrameMetadata> getTblInvFrameMetadatas() {
		return this.tblInvFrameMetadatas;
	}

	public void setTblInvFrameMetadatas(Set<TblInvFrameMetadata> tblInvFrameMetadatas) {
		this.tblInvFrameMetadatas = tblInvFrameMetadatas;
	}

}
