package com.ag.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblInvMaterial generated by hbm2java
 */
@Entity
@Table(name = "tbl_inv_material", catalog = "3d_customer_api", uniqueConstraints = @UniqueConstraint(columnNames = "material"))
public class TblInvMaterial implements java.io.Serializable {

	private Integer id;
	private String material;
	private int order;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private Set<TblInvFrameMetadata> tblInvFrameMetadatasForFrameMaterialId = new HashSet<TblInvFrameMetadata>(0);
	private Set<TblInvFrameMetadata> tblInvFrameMetadatasForTempleMaterialId = new HashSet<TblInvFrameMetadata>(0);

	public TblInvMaterial() {
	}

	public TblInvMaterial(String material, int order, byte isDeleted, Date createDatetime) {
		this.material = material;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblInvMaterial(String material, int order, byte isDeleted, Date createDatetime, Date updateDatetime,
			Set<TblInvFrameMetadata> tblInvFrameMetadatasForFrameMaterialId,
			Set<TblInvFrameMetadata> tblInvFrameMetadatasForTempleMaterialId) {
		this.material = material;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.tblInvFrameMetadatasForFrameMaterialId = tblInvFrameMetadatasForFrameMaterialId;
		this.tblInvFrameMetadatasForTempleMaterialId = tblInvFrameMetadatasForTempleMaterialId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "material", unique = true, nullable = false, length = 100)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvMaterialByFrameMaterialId")
	public Set<TblInvFrameMetadata> getTblInvFrameMetadatasForFrameMaterialId() {
		return this.tblInvFrameMetadatasForFrameMaterialId;
	}

	public void setTblInvFrameMetadatasForFrameMaterialId(
			Set<TblInvFrameMetadata> tblInvFrameMetadatasForFrameMaterialId) {
		this.tblInvFrameMetadatasForFrameMaterialId = tblInvFrameMetadatasForFrameMaterialId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvMaterialByTempleMaterialId")
	public Set<TblInvFrameMetadata> getTblInvFrameMetadatasForTempleMaterialId() {
		return this.tblInvFrameMetadatasForTempleMaterialId;
	}

	public void setTblInvFrameMetadatasForTempleMaterialId(
			Set<TblInvFrameMetadata> tblInvFrameMetadatasForTempleMaterialId) {
		this.tblInvFrameMetadatasForTempleMaterialId = tblInvFrameMetadatasForTempleMaterialId;
	}

}
