package com.ag.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblInvColor generated by hbm2java
 */
@Entity
@Table(name = "tbl_inv_color", catalog = "3d_customer_api", uniqueConstraints = @UniqueConstraint(columnNames = "color"))
public class TblInvColor implements java.io.Serializable {

	private Integer id;
	private String color;
	private Integer colorR;
	private Integer colorG;
	private Integer colorB;
	private int order;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private Set<TblInvFrameMetadata> tblInvFrameMetadatasForGlassColorId = new HashSet<TblInvFrameMetadata>(0);
	private Set<TblInvFrameMetadata> tblInvFrameMetadatasForTempleColorId = new HashSet<TblInvFrameMetadata>(0);
	private Set<TblInvFrameMetadata> tblInvFrameMetadatasForFrameColorId = new HashSet<TblInvFrameMetadata>(0);

	public TblInvColor() {
	}

	public TblInvColor(String color, int order, byte isDeleted, Date createDatetime) {
		this.color = color;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblInvColor(String color, Integer colorR, Integer colorG, Integer colorB, int order, byte isDeleted,
			Date createDatetime, Date updateDatetime, Set<TblInvFrameMetadata> tblInvFrameMetadatasForGlassColorId,
			Set<TblInvFrameMetadata> tblInvFrameMetadatasForTempleColorId,
			Set<TblInvFrameMetadata> tblInvFrameMetadatasForFrameColorId) {
		this.color = color;
		this.colorR = colorR;
		this.colorG = colorG;
		this.colorB = colorB;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.tblInvFrameMetadatasForGlassColorId = tblInvFrameMetadatasForGlassColorId;
		this.tblInvFrameMetadatasForTempleColorId = tblInvFrameMetadatasForTempleColorId;
		this.tblInvFrameMetadatasForFrameColorId = tblInvFrameMetadatasForFrameColorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "color", unique = true, nullable = false, length = 100)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "color_r")
	public Integer getColorR() {
		return this.colorR;
	}

	public void setColorR(Integer colorR) {
		this.colorR = colorR;
	}

	@Column(name = "color_g")
	public Integer getColorG() {
		return this.colorG;
	}

	public void setColorG(Integer colorG) {
		this.colorG = colorG;
	}

	@Column(name = "color_b")
	public Integer getColorB() {
		return this.colorB;
	}

	public void setColorB(Integer colorB) {
		this.colorB = colorB;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvColorByGlassColorId")
	public Set<TblInvFrameMetadata> getTblInvFrameMetadatasForGlassColorId() {
		return this.tblInvFrameMetadatasForGlassColorId;
	}

	public void setTblInvFrameMetadatasForGlassColorId(Set<TblInvFrameMetadata> tblInvFrameMetadatasForGlassColorId) {
		this.tblInvFrameMetadatasForGlassColorId = tblInvFrameMetadatasForGlassColorId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvColorByTempleColorId")
	public Set<TblInvFrameMetadata> getTblInvFrameMetadatasForTempleColorId() {
		return this.tblInvFrameMetadatasForTempleColorId;
	}

	public void setTblInvFrameMetadatasForTempleColorId(Set<TblInvFrameMetadata> tblInvFrameMetadatasForTempleColorId) {
		this.tblInvFrameMetadatasForTempleColorId = tblInvFrameMetadatasForTempleColorId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvColorByFrameColorId")
	public Set<TblInvFrameMetadata> getTblInvFrameMetadatasForFrameColorId() {
		return this.tblInvFrameMetadatasForFrameColorId;
	}

	public void setTblInvFrameMetadatasForFrameColorId(Set<TblInvFrameMetadata> tblInvFrameMetadatasForFrameColorId) {
		this.tblInvFrameMetadatasForFrameColorId = tblInvFrameMetadatasForFrameColorId;
	}

}
