package com.ag.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblInvShape generated by hbm2java
 */
@Entity
@Table(name = "tbl_inv_shape", catalog = "3d_customer_api", uniqueConstraints = @UniqueConstraint(columnNames = "shape"))
public class TblInvShape implements java.io.Serializable {

	private Integer id;
	private String shape;
	private String shapeIcon;
	private int order;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private Set<TblInvFrameMetadata> tblInvFrameMetadatas = new HashSet<TblInvFrameMetadata>(0);

	public TblInvShape() {
	}

	public TblInvShape(String shape, int order, byte isDeleted, Date createDatetime) {
		this.shape = shape;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblInvShape(String shape, String shapeIcon, int order, byte isDeleted, Date createDatetime,
			Date updateDatetime, Set<TblInvFrameMetadata> tblInvFrameMetadatas) {
		this.shape = shape;
		this.shapeIcon = shapeIcon;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.tblInvFrameMetadatas = tblInvFrameMetadatas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "shape", unique = true, nullable = false, length = 100)
	public String getShape() {
		return this.shape;
	}

	public void setShape(String shape) {
		this.shape = shape;
	}

	@Column(name = "shape_icon", length = 200)
	public String getShapeIcon() {
		return this.shapeIcon;
	}

	public void setShapeIcon(String shapeIcon) {
		this.shapeIcon = shapeIcon;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvShape")
	public Set<TblInvFrameMetadata> getTblInvFrameMetadatas() {
		return this.tblInvFrameMetadatas;
	}

	public void setTblInvFrameMetadatas(Set<TblInvFrameMetadata> tblInvFrameMetadatas) {
		this.tblInvFrameMetadatas = tblInvFrameMetadatas;
	}

}
