package com.ag.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblInvCompany generated by hbm2java
 */
@Entity
@Table(name = "tbl_inv_company", catalog = "3d_customer_api", uniqueConstraints = @UniqueConstraint(columnNames = "company"))
public class TblInvCompany implements java.io.Serializable {

	private Integer id;
	private String company;
	private String companyIconUrl;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private Set<TblInvBrand> tblInvBrands = new HashSet<TblInvBrand>(0);

	public TblInvCompany() {
	}

	public TblInvCompany(String company, byte isDeleted, Date createDatetime) {
		this.company = company;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblInvCompany(String company, String companyIconUrl, byte isDeleted, Date createDatetime,
			Date updateDatetime, Set<TblInvBrand> tblInvBrands) {
		this.company = company;
		this.companyIconUrl = companyIconUrl;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.tblInvBrands = tblInvBrands;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "company", unique = true, nullable = false, length = 100)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "company_icon_url", length = 200)
	public String getCompanyIconUrl() {
		return this.companyIconUrl;
	}

	public void setCompanyIconUrl(String companyIconUrl) {
		this.companyIconUrl = companyIconUrl;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvCompany")
	public Set<TblInvBrand> getTblInvBrands() {
		return this.tblInvBrands;
	}

	public void setTblInvBrands(Set<TblInvBrand> tblInvBrands) {
		this.tblInvBrands = tblInvBrands;
	}

}
