package com.ag.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblInvAccountFrame generated by hbm2java
 */
@Entity
@Table(name = "tbl_inv_account_frame", catalog = "3d_customer_api")
public class TblInvAccountFrame implements java.io.Serializable {

	private Integer id;
	private TblInvDistFrame tblInvDistFrame;
	private TblUser tblUser;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private int quantity;
	private BigDecimal price;
	private String priceUnit;
	private Set<TblCollectionAccountFrame> tblCollectionAccountFrames = new HashSet<TblCollectionAccountFrame>(0);
	private Set<TblOrderitems> tblOrderitemses = new HashSet<TblOrderitems>(0);

	public TblInvAccountFrame() {
	}

	public TblInvAccountFrame(TblInvDistFrame tblInvDistFrame, TblUser tblUser, byte isDeleted, Date createDatetime,
			int quantity) {
		this.tblInvDistFrame = tblInvDistFrame;
		this.tblUser = tblUser;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.quantity = quantity;
	}

	public TblInvAccountFrame(TblInvDistFrame tblInvDistFrame, TblUser tblUser, byte isDeleted, Date createDatetime,
			Date updateDatetime, int quantity, BigDecimal price, String priceUnit,
			Set<TblCollectionAccountFrame> tblCollectionAccountFrames, Set<TblOrderitems> tblOrderitemses) {
		this.tblInvDistFrame = tblInvDistFrame;
		this.tblUser = tblUser;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.quantity = quantity;
		this.price = price;
		this.priceUnit = priceUnit;
		this.tblCollectionAccountFrames = tblCollectionAccountFrames;
		this.tblOrderitemses = tblOrderitemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dist_frame_id", nullable = false)
	public TblInvDistFrame getTblInvDistFrame() {
		return this.tblInvDistFrame;
	}

	public void setTblInvDistFrame(TblInvDistFrame tblInvDistFrame) {
		this.tblInvDistFrame = tblInvDistFrame;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_userid", nullable = false)
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "price_unit", length = 20)
	public String getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(String priceUnit) {
		this.priceUnit = priceUnit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvAccountFrame")
	public Set<TblCollectionAccountFrame> getTblCollectionAccountFrames() {
		return this.tblCollectionAccountFrames;
	}

	public void setTblCollectionAccountFrames(Set<TblCollectionAccountFrame> tblCollectionAccountFrames) {
		this.tblCollectionAccountFrames = tblCollectionAccountFrames;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblInvAccountFrame")
	public Set<TblOrderitems> getTblOrderitemses() {
		return this.tblOrderitemses;
	}

	public void setTblOrderitemses(Set<TblOrderitems> tblOrderitemses) {
		this.tblOrderitemses = tblOrderitemses;
	}

}
