package com.ag.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblModel generated by hbm2java
 */
@Entity
@Table(name = "tbl_model", catalog = "3d_customer_api")
public class TblModel implements java.io.Serializable {

	private Integer id;
	private TblInvGender tblInvGender;
	private String modelName;
	private String frontFaceUrl;
	private String jsonUrl;
	private String videoUrl;
	private int order;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private Integer videoFps;

	public TblModel() {
	}

	public TblModel(TblInvGender tblInvGender, String modelName, String jsonUrl, String videoUrl, int order,
			byte isDeleted, Date createDatetime) {
		this.tblInvGender = tblInvGender;
		this.modelName = modelName;
		this.jsonUrl = jsonUrl;
		this.videoUrl = videoUrl;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblModel(TblInvGender tblInvGender, String modelName, String frontFaceUrl, String jsonUrl, String videoUrl,
			int order, byte isDeleted, Date createDatetime, Date updateDatetime, Integer videoFps) {
		this.tblInvGender = tblInvGender;
		this.modelName = modelName;
		this.frontFaceUrl = frontFaceUrl;
		this.jsonUrl = jsonUrl;
		this.videoUrl = videoUrl;
		this.order = order;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.videoFps = videoFps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gender_id", nullable = false)
	public TblInvGender getTblInvGender() {
		return this.tblInvGender;
	}

	public void setTblInvGender(TblInvGender tblInvGender) {
		this.tblInvGender = tblInvGender;
	}

	@Column(name = "model_name", nullable = false, length = 50)
	public String getModelName() {
		return this.modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	@Column(name = "front_face_url", length = 200)
	public String getFrontFaceUrl() {
		return this.frontFaceUrl;
	}

	public void setFrontFaceUrl(String frontFaceUrl) {
		this.frontFaceUrl = frontFaceUrl;
	}

	@Column(name = "json_url", nullable = false, length = 200)
	public String getJsonUrl() {
		return this.jsonUrl;
	}

	public void setJsonUrl(String jsonUrl) {
		this.jsonUrl = jsonUrl;
	}

	@Column(name = "video_url", nullable = false, length = 200)
	public String getVideoUrl() {
		return this.videoUrl;
	}

	public void setVideoUrl(String videoUrl) {
		this.videoUrl = videoUrl;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@Column(name = "video_fps")
	public Integer getVideoFps() {
		return this.videoFps;
	}

	public void setVideoFps(Integer videoFps) {
		this.videoFps = videoFps;
	}

}
