package com.ag.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblOrderitems generated by hbm2java
 */
@Entity
@Table(name = "tbl_orderitems", catalog = "3d_customer_api")
public class TblOrderitems implements java.io.Serializable {

	private Integer id;
	private TblInvAccountFrame tblInvAccountFrame;
	private TblInvDistFrame tblInvDistFrame;
	private TblInvFrameMetadata tblInvFrameMetadata;
	private TblOrderAccount tblOrderAccount;
	private TblOrderDistributor tblOrderDistributor;
	private TblOrderStatus tblOrderStatus;
	private TblUser tblUser;
	private int quantityOriginal;
	private Integer quantityApproved;
	private Integer quantityDelivered;
	private Date orderDatetime;
	private Date approvedDatetime;
	private Date deliveredDatetime;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private BigDecimal priceOriginal;
	private BigDecimal priceDelivered;
	private String priceUnit;

	public TblOrderitems() {
	}

	public TblOrderitems(TblInvAccountFrame tblInvAccountFrame, TblInvFrameMetadata tblInvFrameMetadata,
			TblOrderStatus tblOrderStatus, TblUser tblUser, int quantityOriginal, Date orderDatetime, byte isDeleted,
			Date createDatetime) {
		this.tblInvAccountFrame = tblInvAccountFrame;
		this.tblInvFrameMetadata = tblInvFrameMetadata;
		this.tblOrderStatus = tblOrderStatus;
		this.tblUser = tblUser;
		this.quantityOriginal = quantityOriginal;
		this.orderDatetime = orderDatetime;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblOrderitems(TblInvAccountFrame tblInvAccountFrame, TblInvDistFrame tblInvDistFrame,
			TblInvFrameMetadata tblInvFrameMetadata, TblOrderAccount tblOrderAccount,
			TblOrderDistributor tblOrderDistributor, TblOrderStatus tblOrderStatus, TblUser tblUser,
			int quantityOriginal, Integer quantityApproved, Integer quantityDelivered, Date orderDatetime,
			Date approvedDatetime, Date deliveredDatetime, byte isDeleted, Date createDatetime, Date updateDatetime,
			BigDecimal priceOriginal, BigDecimal priceDelivered, String priceUnit) {
		this.tblInvAccountFrame = tblInvAccountFrame;
		this.tblInvDistFrame = tblInvDistFrame;
		this.tblInvFrameMetadata = tblInvFrameMetadata;
		this.tblOrderAccount = tblOrderAccount;
		this.tblOrderDistributor = tblOrderDistributor;
		this.tblOrderStatus = tblOrderStatus;
		this.tblUser = tblUser;
		this.quantityOriginal = quantityOriginal;
		this.quantityApproved = quantityApproved;
		this.quantityDelivered = quantityDelivered;
		this.orderDatetime = orderDatetime;
		this.approvedDatetime = approvedDatetime;
		this.deliveredDatetime = deliveredDatetime;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.priceOriginal = priceOriginal;
		this.priceDelivered = priceDelivered;
		this.priceUnit = priceUnit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_frameid", nullable = false)
	public TblInvAccountFrame getTblInvAccountFrame() {
		return this.tblInvAccountFrame;
	}

	public void setTblInvAccountFrame(TblInvAccountFrame tblInvAccountFrame) {
		this.tblInvAccountFrame = tblInvAccountFrame;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dist_frameid")
	public TblInvDistFrame getTblInvDistFrame() {
		return this.tblInvDistFrame;
	}

	public void setTblInvDistFrame(TblInvDistFrame tblInvDistFrame) {
		this.tblInvDistFrame = tblInvDistFrame;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frame_id", nullable = false)
	public TblInvFrameMetadata getTblInvFrameMetadata() {
		return this.tblInvFrameMetadata;
	}

	public void setTblInvFrameMetadata(TblInvFrameMetadata tblInvFrameMetadata) {
		this.tblInvFrameMetadata = tblInvFrameMetadata;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_order_id")
	public TblOrderAccount getTblOrderAccount() {
		return this.tblOrderAccount;
	}

	public void setTblOrderAccount(TblOrderAccount tblOrderAccount) {
		this.tblOrderAccount = tblOrderAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "distributor_order_id")
	public TblOrderDistributor getTblOrderDistributor() {
		return this.tblOrderDistributor;
	}

	public void setTblOrderDistributor(TblOrderDistributor tblOrderDistributor) {
		this.tblOrderDistributor = tblOrderDistributor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_status_id", nullable = false)
	public TblOrderStatus getTblOrderStatus() {
		return this.tblOrderStatus;
	}

	public void setTblOrderStatus(TblOrderStatus tblOrderStatus) {
		this.tblOrderStatus = tblOrderStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderby_id", nullable = false)
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@Column(name = "quantity_original", nullable = false)
	public int getQuantityOriginal() {
		return this.quantityOriginal;
	}

	public void setQuantityOriginal(int quantityOriginal) {
		this.quantityOriginal = quantityOriginal;
	}

	@Column(name = "quantity_approved")
	public Integer getQuantityApproved() {
		return this.quantityApproved;
	}

	public void setQuantityApproved(Integer quantityApproved) {
		this.quantityApproved = quantityApproved;
	}

	@Column(name = "quantity_delivered")
	public Integer getQuantityDelivered() {
		return this.quantityDelivered;
	}

	public void setQuantityDelivered(Integer quantityDelivered) {
		this.quantityDelivered = quantityDelivered;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_datetime", nullable = false, length = 19)
	public Date getOrderDatetime() {
		return this.orderDatetime;
	}

	public void setOrderDatetime(Date orderDatetime) {
		this.orderDatetime = orderDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approved_datetime", length = 19)
	public Date getApprovedDatetime() {
		return this.approvedDatetime;
	}

	public void setApprovedDatetime(Date approvedDatetime) {
		this.approvedDatetime = approvedDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delivered_datetime", length = 19)
	public Date getDeliveredDatetime() {
		return this.deliveredDatetime;
	}

	public void setDeliveredDatetime(Date deliveredDatetime) {
		this.deliveredDatetime = deliveredDatetime;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@Column(name = "price_original", precision = 10)
	public BigDecimal getPriceOriginal() {
		return this.priceOriginal;
	}

	public void setPriceOriginal(BigDecimal priceOriginal) {
		this.priceOriginal = priceOriginal;
	}

	@Column(name = "price_delivered", precision = 10)
	public BigDecimal getPriceDelivered() {
		return this.priceDelivered;
	}

	public void setPriceDelivered(BigDecimal priceDelivered) {
		this.priceDelivered = priceDelivered;
	}

	@Column(name = "price_unit", length = 20)
	public String getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(String priceUnit) {
		this.priceUnit = priceUnit;
	}

}
