package com.ag.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblOrderStatus generated by hbm2java
 */
@Entity
@Table(name = "tbl_order_status", catalog = "3d_customer_api", uniqueConstraints = @UniqueConstraint(columnNames = "status"))
public class TblOrderStatus implements java.io.Serializable {

	private Integer id;
	private String status;
	private String description;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private Set<TblOrderAccount> tblOrderAccounts = new HashSet<TblOrderAccount>(0);
	private Set<TblOrderDistributor> tblOrderDistributors = new HashSet<TblOrderDistributor>(0);
	private Set<TblOrderitems> tblOrderitemses = new HashSet<TblOrderitems>(0);

	public TblOrderStatus() {
	}

	public TblOrderStatus(String status, byte isDeleted, Date createDatetime) {
		this.status = status;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblOrderStatus(String status, String description, byte isDeleted, Date createDatetime, Date updateDatetime,
			Set<TblOrderAccount> tblOrderAccounts, Set<TblOrderDistributor> tblOrderDistributors,
			Set<TblOrderitems> tblOrderitemses) {
		this.status = status;
		this.description = description;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.tblOrderAccounts = tblOrderAccounts;
		this.tblOrderDistributors = tblOrderDistributors;
		this.tblOrderitemses = tblOrderitemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "status", unique = true, nullable = false, length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblOrderStatus")
	public Set<TblOrderAccount> getTblOrderAccounts() {
		return this.tblOrderAccounts;
	}

	public void setTblOrderAccounts(Set<TblOrderAccount> tblOrderAccounts) {
		this.tblOrderAccounts = tblOrderAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblOrderStatus")
	public Set<TblOrderDistributor> getTblOrderDistributors() {
		return this.tblOrderDistributors;
	}

	public void setTblOrderDistributors(Set<TblOrderDistributor> tblOrderDistributors) {
		this.tblOrderDistributors = tblOrderDistributors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblOrderStatus")
	public Set<TblOrderitems> getTblOrderitemses() {
		return this.tblOrderitemses;
	}

	public void setTblOrderitemses(Set<TblOrderitems> tblOrderitemses) {
		this.tblOrderitemses = tblOrderitemses;
	}

}
