package com.ag.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUserAccountStore generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_account_store", catalog = "3d_customer_api")
public class TblUserAccountStore implements java.io.Serializable {

	private Integer id;
	private TblUser tblUserByAccountUserid;
	private TblUser tblUserByStoreUserid;
	private Date storeAdditionDatetime;
	private Date storeDeletionDatetime;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;

	public TblUserAccountStore() {
	}

	public TblUserAccountStore(TblUser tblUserByAccountUserid, TblUser tblUserByStoreUserid, Date storeAdditionDatetime,
			byte isDeleted, Date createDatetime) {
		this.tblUserByAccountUserid = tblUserByAccountUserid;
		this.tblUserByStoreUserid = tblUserByStoreUserid;
		this.storeAdditionDatetime = storeAdditionDatetime;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblUserAccountStore(TblUser tblUserByAccountUserid, TblUser tblUserByStoreUserid, Date storeAdditionDatetime,
			Date storeDeletionDatetime, byte isDeleted, Date createDatetime, Date updateDatetime) {
		this.tblUserByAccountUserid = tblUserByAccountUserid;
		this.tblUserByStoreUserid = tblUserByStoreUserid;
		this.storeAdditionDatetime = storeAdditionDatetime;
		this.storeDeletionDatetime = storeDeletionDatetime;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_userid", nullable = false)
	public TblUser getTblUserByAccountUserid() {
		return this.tblUserByAccountUserid;
	}

	public void setTblUserByAccountUserid(TblUser tblUserByAccountUserid) {
		this.tblUserByAccountUserid = tblUserByAccountUserid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_userid", nullable = false)
	public TblUser getTblUserByStoreUserid() {
		return this.tblUserByStoreUserid;
	}

	public void setTblUserByStoreUserid(TblUser tblUserByStoreUserid) {
		this.tblUserByStoreUserid = tblUserByStoreUserid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "store_addition_datetime", nullable = false, length = 19)
	public Date getStoreAdditionDatetime() {
		return this.storeAdditionDatetime;
	}

	public void setStoreAdditionDatetime(Date storeAdditionDatetime) {
		this.storeAdditionDatetime = storeAdditionDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "store_deletion_datetime", length = 19)
	public Date getStoreDeletionDatetime() {
		return this.storeDeletionDatetime;
	}

	public void setStoreDeletionDatetime(Date storeDeletionDatetime) {
		this.storeDeletionDatetime = storeDeletionDatetime;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
