package com.ag.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUserDistAccount generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_dist_account", catalog = "3d_customer_api")
public class TblUserDistAccount implements java.io.Serializable {

	private Integer id;
	private TblUser tblUserByDistUserid;
	private TblUser tblUserByAccountUserid;
	private Date validFrom;
	private Date validThru;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;

	public TblUserDistAccount() {
	}

	public TblUserDistAccount(TblUser tblUserByDistUserid, TblUser tblUserByAccountUserid, Date validFrom,
			byte isDeleted, Date createDatetime) {
		this.tblUserByDistUserid = tblUserByDistUserid;
		this.tblUserByAccountUserid = tblUserByAccountUserid;
		this.validFrom = validFrom;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblUserDistAccount(TblUser tblUserByDistUserid, TblUser tblUserByAccountUserid, Date validFrom,
			Date validThru, byte isDeleted, Date createDatetime, Date updateDatetime) {
		this.tblUserByDistUserid = tblUserByDistUserid;
		this.tblUserByAccountUserid = tblUserByAccountUserid;
		this.validFrom = validFrom;
		this.validThru = validThru;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dist_userid", nullable = false)
	public TblUser getTblUserByDistUserid() {
		return this.tblUserByDistUserid;
	}

	public void setTblUserByDistUserid(TblUser tblUserByDistUserid) {
		this.tblUserByDistUserid = tblUserByDistUserid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_userid", nullable = false)
	public TblUser getTblUserByAccountUserid() {
		return this.tblUserByAccountUserid;
	}

	public void setTblUserByAccountUserid(TblUser tblUserByAccountUserid) {
		this.tblUserByAccountUserid = tblUserByAccountUserid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valid_from", nullable = false, length = 19)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valid_thru", length = 19)
	public Date getValidThru() {
		return this.validThru;
	}

	public void setValidThru(Date validThru) {
		this.validThru = validThru;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
