package com.ag.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblUserType generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_type", catalog = "3d_customer_api", uniqueConstraints = @UniqueConstraint(columnNames = "user_type"))
public class TblUserType implements java.io.Serializable {

	private Integer id;
	private String userType;
	private String description;
	private byte isDeleted;
	private Date createDatetime;
	private Date updateDatetime;
	private Set<TblUser> tblUsers = new HashSet<TblUser>(0);

	public TblUserType() {
	}

	public TblUserType(String userType, byte isDeleted, Date createDatetime) {
		this.userType = userType;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
	}

	public TblUserType(String userType, String description, byte isDeleted, Date createDatetime, Date updateDatetime,
			Set<TblUser> tblUsers) {
		this.userType = userType;
		this.description = description;
		this.isDeleted = isDeleted;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.tblUsers = tblUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_type", unique = true, nullable = false, length = 50)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "is_deleted", nullable = false)
	public byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 19)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblUserType")
	public Set<TblUser> getTblUsers() {
		return this.tblUsers;
	}

	public void setTblUsers(Set<TblUser> tblUsers) {
		this.tblUsers = tblUsers;
	}

}
